// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  alternating_text: dynamic(() => import("./AlternatingText")),
  big_text: dynamic(() => import("./BigText")),
  caroussel: dynamic(() => import("./Caroussel")),
  hero: dynamic(() => import("./Hero")),
  sky_dive: dynamic(() => import("./SkyDive")),
};
