import type { Metadata } from "next";
import localFont from "next/font/local"
import "./globals.css";
import Header from "@/components/Header";
import ViewCanvas from "@/components/ViewCanvas";
import Footer from "@/components/Footer";


const alpino = localFont({
  src: "../public/fonts/Alpino-Variable.woff2",
  weight: "100 900",
  display: "swap",
  variable: "--font-alpino"
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={alpino.variable}>
      <body className=" overflow-x-hidden bg-yellow-300">
        <Header/>
        <main>
          {children}
          <ViewCanvas/>
        </main>
        <Footer/>
      </body>
    </html>
  );
}
